title: DeepDive
description: A deep dive into the physics of the first massive quiescent galaxies in the Universe
theme: jekyll-theme-cayman

url: "https://fmvalentino.github.io"
baseurl: "/deepdive"

include:
  - sitemap.xml
  - robots.txt